# Generated by Django 4.0.8 on 2022-12-31 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_budget_remaining_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='users',
        ),
        migrations.DeleteModel(
            name='Budget',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
