# Generated by Django 4.0.8 on 2022-12-31 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='non_members',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
